### ISSUE TITLE
How to use project

### ISSUE THREAD

**Issue by nanzo74** [couchbaselabs/cb-swagger#2]
Hi, 
I just came across your project while researching Swagger in DITA. I work on a Windows machine and don't use Python. Are there any setup steps that I can follow to use your solution?
Thanks in advance,
Ann

**Comment by mattcarabine** [comment]
Hey @nanzo74,

Currently this is an internal (WIP) project, as such not much work has been done to make the project widely usable.

For example:
- The project only outputs a single template
- The project assumes that the swagger spec has certain fields (e.g. `x-dita-path`)
- The project assumes certain environments (e.g. no specific instructions for Windows) 

I will be spending some more time working on this soon, so if you could let me know more about your use case, then I should be able to factor this in (and hopefully be able to make the project more useful to others in the process).

Cheers,
Matt

**Comment by nanzo74** [comment]
Hi Matt,
So I am new to API documentation and researching how I can document our internal APIs. For our existing product documentation we are using DITA in Oxgyen XML Author publishing to Oxygen WebHelp and PDF (for both internal technical audience and external business audience). Our internal developers' Web API configuration uses SwashBuckle in .NET so that we have Swagger UI output (and API json definition) available. I want to explore if I can work with the API json definition to convert it to DITA so that API documentation can be marked up in DITA also.
Regards,
Ann

**Comment by bhavyas0811** [comment]
> Hi Matt,
> So I am new to API documentation and researching how I can document our internal APIs. For our existing product documentation we are using DITA in Oxgyen XML Author publishing to Oxygen WebHelp and PDF (for both internal technical audience and external business audience). Our internal developers' Web API configuration uses SwashBuckle in .NET so that we have Swagger UI output (and API json definition) available. I want to explore if I can work with the API json definition to convert it to DITA so that API documentation can be marked up in DITA also.
> Regards,
> Ann

Hey guys,

Any updates on this? I am looking for the same requirement.

Regards,
Bhavya S
